// This file is auto-generated by @hey-api/openapi-ts

import { type Client, formDataBodySerializer, type Options as Options2, type TDataShape } from './client';
import { client } from './client.gen';
import type { CancelEditEditsEditIdCancelPostData, CancelEditEditsEditIdCancelPostErrors, CancelEditEditsEditIdCancelPostResponses, CreateWorkflowWorkflowsPostData, CreateWorkflowWorkflowsPostErrors, CreateWorkflowWorkflowsPostResponses, DeleteFileFromBucketBucketFilesFileIdDeleteData, DeleteFileFromBucketBucketFilesFileIdDeleteErrors, DeleteFileFromBucketBucketFilesFileIdDeleteResponses, EditVideoEditsPostData, EditVideoEditsPostErrors, EditVideoEditsPostResponses, ExecuteWorkflowWorkflowsExecutePostData, ExecuteWorkflowWorkflowsExecutePostErrors, ExecuteWorkflowWorkflowsExecutePostResponses, GetEditEditsEditIdGetData, GetEditEditsEditIdGetErrors, GetEditEditsEditIdGetResponses, GetWorkflowWorkflowsWorkflowIdGetData, GetWorkflowWorkflowsWorkflowIdGetErrors, GetWorkflowWorkflowsWorkflowIdGetResponses, ListEditsEditsGetData, ListEditsEditsGetErrors, ListEditsEditsGetResponses, ListFilesBucketGetData, ListFilesBucketGetErrors, ListFilesBucketGetResponses, ListWorkflowsWorkflowsGetData, ListWorkflowsWorkflowsGetErrors, ListWorkflowsWorkflowsGetResponses, RetryEditEditsEditIdRetryPostData, RetryEditEditsEditIdRetryPostErrors, RetryEditEditsEditIdRetryPostResponses, RetryWorkflowWorkflowsWorkflowIdRetryPostData, RetryWorkflowWorkflowsWorkflowIdRetryPostErrors, RetryWorkflowWorkflowsWorkflowIdRetryPostResponses, StreamJobsEditsStatusGetData, StreamJobsEditsStatusGetErrors, StreamJobsEditsStatusGetResponses, UpdateEditEditsEditIdPatchData, UpdateEditEditsEditIdPatchErrors, UpdateEditEditsEditIdPatchResponses, UpdateWorkflowWorkflowsWorkflowIdPatchData, UpdateWorkflowWorkflowsWorkflowIdPatchErrors, UpdateWorkflowWorkflowsWorkflowIdPatchResponses, UploadFileToBucketBucketUploadPostData, UploadFileToBucketBucketUploadPostErrors, UploadFileToBucketBucketUploadPostResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Upload File To Bucket
 */
export const uploadFileToBucketBucketUploadPost = <ThrowOnError extends boolean = false>(options: Options<UploadFileToBucketBucketUploadPostData, ThrowOnError>) => (options.client ?? client).post<UploadFileToBucketBucketUploadPostResponses, UploadFileToBucketBucketUploadPostErrors, ThrowOnError>({
    ...formDataBodySerializer,
    url: '/bucket/upload',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * List Files
 */
export const listFilesBucketGet = <ThrowOnError extends boolean = false>(options?: Options<ListFilesBucketGetData, ThrowOnError>) => (options?.client ?? client).get<ListFilesBucketGetResponses, ListFilesBucketGetErrors, ThrowOnError>({ url: '/bucket/', ...options });

/**
 * Delete File From Bucket
 */
export const deleteFileFromBucketBucketFilesFileIdDelete = <ThrowOnError extends boolean = false>(options: Options<DeleteFileFromBucketBucketFilesFileIdDeleteData, ThrowOnError>) => (options.client ?? client).delete<DeleteFileFromBucketBucketFilesFileIdDeleteResponses, DeleteFileFromBucketBucketFilesFileIdDeleteErrors, ThrowOnError>({ url: '/bucket/files/{file_id}', ...options });

/**
 * List Edits
 */
export const listEditsEditsGet = <ThrowOnError extends boolean = false>(options?: Options<ListEditsEditsGetData, ThrowOnError>) => (options?.client ?? client).get<ListEditsEditsGetResponses, ListEditsEditsGetErrors, ThrowOnError>({ url: '/edits', ...options });

/**
 * Edit Video
 */
export const editVideoEditsPost = <ThrowOnError extends boolean = false>(options: Options<EditVideoEditsPostData, ThrowOnError>) => (options.client ?? client).post<EditVideoEditsPostResponses, EditVideoEditsPostErrors, ThrowOnError>({
    url: '/edits',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Stream Jobs
 */
export const streamJobsEditsStatusGet = <ThrowOnError extends boolean = false>(options: Options<StreamJobsEditsStatusGetData, ThrowOnError>) => (options.client ?? client).get<StreamJobsEditsStatusGetResponses, StreamJobsEditsStatusGetErrors, ThrowOnError>({ url: '/edits/status', ...options });

/**
 * Get Edit
 */
export const getEditEditsEditIdGet = <ThrowOnError extends boolean = false>(options: Options<GetEditEditsEditIdGetData, ThrowOnError>) => (options.client ?? client).get<GetEditEditsEditIdGetResponses, GetEditEditsEditIdGetErrors, ThrowOnError>({ url: '/edits/{edit_id}', ...options });

/**
 * Update Edit
 */
export const updateEditEditsEditIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateEditEditsEditIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateEditEditsEditIdPatchResponses, UpdateEditEditsEditIdPatchErrors, ThrowOnError>({
    url: '/edits/{edit_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retry Edit
 */
export const retryEditEditsEditIdRetryPost = <ThrowOnError extends boolean = false>(options: Options<RetryEditEditsEditIdRetryPostData, ThrowOnError>) => (options.client ?? client).post<RetryEditEditsEditIdRetryPostResponses, RetryEditEditsEditIdRetryPostErrors, ThrowOnError>({ url: '/edits/{edit_id}/retry', ...options });

/**
 * Cancel Edit
 */
export const cancelEditEditsEditIdCancelPost = <ThrowOnError extends boolean = false>(options: Options<CancelEditEditsEditIdCancelPostData, ThrowOnError>) => (options.client ?? client).post<CancelEditEditsEditIdCancelPostResponses, CancelEditEditsEditIdCancelPostErrors, ThrowOnError>({ url: '/edits/{edit_id}/cancel', ...options });

/**
 * List Workflows
 */
export const listWorkflowsWorkflowsGet = <ThrowOnError extends boolean = false>(options?: Options<ListWorkflowsWorkflowsGetData, ThrowOnError>) => (options?.client ?? client).get<ListWorkflowsWorkflowsGetResponses, ListWorkflowsWorkflowsGetErrors, ThrowOnError>({ url: '/workflows', ...options });

/**
 * Create Workflow
 */
export const createWorkflowWorkflowsPost = <ThrowOnError extends boolean = false>(options: Options<CreateWorkflowWorkflowsPostData, ThrowOnError>) => (options.client ?? client).post<CreateWorkflowWorkflowsPostResponses, CreateWorkflowWorkflowsPostErrors, ThrowOnError>({
    url: '/workflows',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Get Workflow
 */
export const getWorkflowWorkflowsWorkflowIdGet = <ThrowOnError extends boolean = false>(options: Options<GetWorkflowWorkflowsWorkflowIdGetData, ThrowOnError>) => (options.client ?? client).get<GetWorkflowWorkflowsWorkflowIdGetResponses, GetWorkflowWorkflowsWorkflowIdGetErrors, ThrowOnError>({ url: '/workflows/{workflow_id}', ...options });

/**
 * Update Workflow
 */
export const updateWorkflowWorkflowsWorkflowIdPatch = <ThrowOnError extends boolean = false>(options: Options<UpdateWorkflowWorkflowsWorkflowIdPatchData, ThrowOnError>) => (options.client ?? client).patch<UpdateWorkflowWorkflowsWorkflowIdPatchResponses, UpdateWorkflowWorkflowsWorkflowIdPatchErrors, ThrowOnError>({
    url: '/workflows/{workflow_id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Retry Workflow
 */
export const retryWorkflowWorkflowsWorkflowIdRetryPost = <ThrowOnError extends boolean = false>(options: Options<RetryWorkflowWorkflowsWorkflowIdRetryPostData, ThrowOnError>) => (options.client ?? client).post<RetryWorkflowWorkflowsWorkflowIdRetryPostResponses, RetryWorkflowWorkflowsWorkflowIdRetryPostErrors, ThrowOnError>({
    url: '/workflows/{workflow_id}/retry',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Execute Workflow
 */
export const executeWorkflowWorkflowsExecutePost = <ThrowOnError extends boolean = false>(options: Options<ExecuteWorkflowWorkflowsExecutePostData, ThrowOnError>) => (options.client ?? client).post<ExecuteWorkflowWorkflowsExecutePostResponses, ExecuteWorkflowWorkflowsExecutePostErrors, ThrowOnError>({ url: '/workflows/execute', ...options });
