// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:8000' | (string & {});
};

/**
 * AudioOp
 */
export type AudioOp = {
    /**
     * Op
     */
    op: 'audio';
    /**
     * Path
     */
    path?: string | null;
    /**
     * Mix Volume
     */
    mix_volume?: number;
    /**
     * Loop
     */
    loop?: boolean;
    overlay?: AudioOverlay | null;
};

/**
 * AudioOverlay
 *
 * Background or mix-in audio (e.g. music).
 */
export type AudioOverlay = {
    /**
     * Path
     */
    path: string;
    /**
     * Mix Volume
     */
    mix_volume?: number;
    /**
     * Loop
     */
    loop?: boolean;
};

/**
 * BackgroundColor
 *
 * Solid background color. only_color=True means output is just the color (no source video).
 */
export type BackgroundColor = {
    /**
     * Color
     */
    color?: string;
    /**
     * Only Color
     */
    only_color?: boolean;
};

/**
 * BackgroundColorOp
 */
export type BackgroundColorOp = {
    /**
     * Op
     */
    op: 'backgroundColor';
    overlay: BackgroundColor;
};

/**
 * Body_upload_file_to_bucket_bucket_upload_post
 */
export type BodyUploadFileToBucketBucketUploadPost = {
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CompressOp
 */
export type CompressOp = {
    /**
     * Op
     */
    op: 'compress';
    /**
     * Target Size Mb
     */
    target_size_mb?: number | null;
    /**
     * Scale
     */
    scale?: string | null;
    /**
     * Preset
     */
    preset?: string;
};

/**
 * ConcatOp
 */
export type ConcatOp = {
    /**
     * Op
     */
    op: 'concat';
    /**
     * Input Paths
     */
    input_paths: Array<string>;
};

/**
 * EditUpdateRequest
 */
export type EditUpdateRequest = {
    /**
     * Status
     */
    status?: string | null;
    /**
     * Progress
     */
    progress?: number | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * ExtractAudioOp
 */
export type ExtractAudioOp = {
    /**
     * Op
     */
    op: 'extractAudio';
};

/**
 * GifOp
 */
export type GifOp = {
    /**
     * Op
     */
    op: 'gif';
    /**
     * Start Time
     */
    start_time?: string;
    /**
     * Duration
     */
    duration?: number;
    /**
     * Fps
     */
    fps?: number;
    /**
     * Scale
     */
    scale?: number;
    /**
     * Output Codec
     */
    output_codec?: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * SpeedOp
 */
export type SpeedOp = {
    /**
     * Op
     */
    op: 'speed';
    /**
     * Segment
     */
    segment: Array<SpeedSegment>;
};

/**
 * SpeedSegment
 *
 * Speed override for a time range. end_sec=-1 means till the end of the video.
 */
export type SpeedSegment = {
    /**
     * Start Sec
     */
    start_sec?: number;
    /**
     * End Sec
     */
    end_sec?: number;
    /**
     * Speed
     */
    speed?: number;
};

/**
 * TextOp
 */
export type TextOp = {
    /**
     * Op
     */
    op: 'text';
    /**
     * Segment
     */
    segment: Array<TextSegment>;
};

/**
 * TextSegment
 *
 * Text overlay for a time range. end_sec=-1 means till the end of the video.
 */
export type TextSegment = {
    /**
     * Start Sec
     */
    start_sec: number;
    /**
     * End Sec
     */
    end_sec: number;
    /**
     * Text
     */
    text: string;
    /**
     * Fontsize
     */
    fontsize?: number;
    /**
     * X
     */
    x?: string;
    /**
     * Y
     */
    y?: string;
    /**
     * Fontfile
     */
    fontfile?: string | null;
    /**
     * Fontcolor
     */
    fontcolor?: string | null;
    /**
     * Boxcolor
     */
    boxcolor?: string | null;
    /**
     * Boxborderw
     */
    boxborderw?: number | null;
    /**
     * Background
     */
    background?: boolean | null;
};

/**
 * TranscodeOp
 */
export type TranscodeOp = {
    /**
     * Op
     */
    op: 'transcode';
    /**
     * Codec
     */
    codec?: string;
    /**
     * Preset
     */
    preset?: string;
    /**
     * Crf
     */
    crf?: number;
    /**
     * Audio Codec
     */
    audio_codec?: string;
    /**
     * Movflags
     */
    movflags?: string | null;
    options?: TranscodeOptions | null;
};

/**
 * TranscodeOptions
 *
 * Encoding options for transcode/compress. Matches common ffmpeg transcode API.
 */
export type TranscodeOptions = {
    /**
     * Codec
     */
    codec?: string;
    /**
     * Preset
     */
    preset?: string;
    /**
     * Crf
     */
    crf?: number;
    /**
     * Audio Codec
     */
    audio_codec?: string;
    /**
     * Audio Bitrate
     */
    audio_bitrate?: string | null;
    /**
     * Movflags
     */
    movflags?: string | null;
    /**
     * Target Size Mb
     */
    target_size_mb?: number | null;
    /**
     * Scale
     */
    scale?: string | null;
};

/**
 * TrimOp
 */
export type TrimOp = {
    /**
     * Op
     */
    op: 'trim';
    /**
     * Start Sec
     */
    start_sec?: number;
    /**
     * End Sec
     */
    end_sec?: number;
    /**
     * Duration
     */
    duration?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VideoEditRequest
 */
export type VideoEditRequest = {
    /**
     * Media
     */
    media: string;
    /**
     * Operations
     */
    operations: Array<({
        op: 'trim';
    } & TrimOp) | ({
        op: 'text';
    } & TextOp) | ({
        op: 'speed';
    } & SpeedOp) | ({
        op: 'watermark';
    } & WatermarkOpInput) | ({
        op: 'audio';
    } & AudioOp) | ({
        op: 'backgroundColor';
    } & BackgroundColorOp) | ({
        op: 'transcode';
    } & TranscodeOp) | ({
        op: 'compress';
    } & CompressOp) | ({
        op: 'concat';
    } & ConcatOp) | ({
        op: 'extractAudio';
    } & ExtractAudioOp) | ({
        op: 'gif';
    } & GifOp)>;
};

/**
 * VideoWorkflowCreateRequest
 */
export type VideoWorkflowCreateRequestInput = {
    /**
     * Name
     */
    name: string;
    /**
     * Steps
     */
    steps: Array<Array<({
        op: 'trim';
    } & TrimOp) | ({
        op: 'text';
    } & TextOp) | ({
        op: 'speed';
    } & SpeedOp) | ({
        op: 'watermark';
    } & WatermarkOpInput) | ({
        op: 'audio';
    } & AudioOp) | ({
        op: 'backgroundColor';
    } & BackgroundColorOp) | ({
        op: 'transcode';
    } & TranscodeOp) | ({
        op: 'compress';
    } & CompressOp) | ({
        op: 'concat';
    } & ConcatOp) | ({
        op: 'extractAudio';
    } & ExtractAudioOp) | ({
        op: 'gif';
    } & GifOp)>>;
    /**
     * Search
     */
    search?: string | null;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * VideoWorkflowCreateRequest
 */
export type VideoWorkflowCreateRequestOutput = {
    /**
     * Name
     */
    name: string;
    /**
     * Steps
     */
    steps: Array<Array<({
        op: 'trim';
    } & TrimOp) | ({
        op: 'text';
    } & TextOp) | ({
        op: 'speed';
    } & SpeedOp) | ({
        op: 'watermark';
    } & WatermarkOpOutput) | ({
        op: 'audio';
    } & AudioOp) | ({
        op: 'backgroundColor';
    } & BackgroundColorOp) | ({
        op: 'transcode';
    } & TranscodeOp) | ({
        op: 'compress';
    } & CompressOp) | ({
        op: 'concat';
    } & ConcatOp) | ({
        op: 'extractAudio';
    } & ExtractAudioOp) | ({
        op: 'gif';
    } & GifOp)>>;
    /**
     * Search
     */
    search?: string | null;
    /**
     * Id
     */
    id?: number | null;
    /**
     * Created At
     */
    created_at?: string;
    /**
     * Updated At
     */
    updated_at?: string;
};

/**
 * WatermarkOp
 */
export type WatermarkOpInput = {
    /**
     * Op
     */
    op: 'watermark';
    overlay: WatermarkOverlay;
};

/**
 * WatermarkOp
 */
export type WatermarkOpOutput = {
    /**
     * Op
     */
    op: 'watermark';
    overlay: WatermarkOverlay;
};

/**
 * WatermarkOverlay
 *
 * Watermark image overlay on video.
 */
export type WatermarkOverlay = {
    /**
     * Path
     */
    path: string;
    position?: WatermarkPosition;
    /**
     * Opacity
     */
    opacity?: number;
};

/**
 * WatermarkPosition
 */
export type WatermarkPosition = '10:10' | '(W-w)/2:10' | 'W-w-10:10' | '10:(H-h)/2' | '(W-w)/2:(H-h)/2' | 'W-w-10:(H-h)/2' | '10:H-h-10' | '(W-w)/2:H-h-10' | 'W-w-10:H-h-10' | '(W-w)/2:80' | '(W-w)/2:H-h-80';

/**
 * WorkflowRetryRequest
 */
export type WorkflowRetryRequest = {
    /**
     * Uid
     */
    uid: string;
};

/**
 * WorkflowUpdateRequest
 */
export type WorkflowUpdateRequest = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Search
     */
    search?: string | null;
    /**
     * Steps
     */
    steps?: Array<Array<{
        [key: string]: unknown;
    }>> | null;
};

export type UploadFileToBucketBucketUploadPostData = {
    body: BodyUploadFileToBucketBucketUploadPost;
    path?: never;
    query?: never;
    url: '/bucket/upload';
};

export type UploadFileToBucketBucketUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UploadFileToBucketBucketUploadPostError = UploadFileToBucketBucketUploadPostErrors[keyof UploadFileToBucketBucketUploadPostErrors];

export type UploadFileToBucketBucketUploadPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListFilesBucketGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/bucket/';
};

export type ListFilesBucketGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListFilesBucketGetError = ListFilesBucketGetErrors[keyof ListFilesBucketGetErrors];

export type ListFilesBucketGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteFileFromBucketBucketFilesFileIdDeleteData = {
    body?: never;
    path: {
        /**
         * File Id
         */
        file_id: number;
    };
    query?: never;
    url: '/bucket/files/{file_id}';
};

export type DeleteFileFromBucketBucketFilesFileIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteFileFromBucketBucketFilesFileIdDeleteError = DeleteFileFromBucketBucketFilesFileIdDeleteErrors[keyof DeleteFileFromBucketBucketFilesFileIdDeleteErrors];

export type DeleteFileFromBucketBucketFilesFileIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListEditsEditsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Uid
         */
        uid?: string | null;
        /**
         * Status
         */
        status?: string | null;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Last Id
         */
        last_id?: number;
    };
    url: '/edits';
};

export type ListEditsEditsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListEditsEditsGetError = ListEditsEditsGetErrors[keyof ListEditsEditsGetErrors];

export type ListEditsEditsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type EditVideoEditsPostData = {
    body: VideoEditRequest;
    path?: never;
    query?: never;
    url: '/edits';
};

export type EditVideoEditsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type EditVideoEditsPostError = EditVideoEditsPostErrors[keyof EditVideoEditsPostErrors];

export type EditVideoEditsPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type StreamJobsEditsStatusGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Uid
         */
        uid: string;
    };
    url: '/edits/status';
};

export type StreamJobsEditsStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamJobsEditsStatusGetError = StreamJobsEditsStatusGetErrors[keyof StreamJobsEditsStatusGetErrors];

export type StreamJobsEditsStatusGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetEditEditsEditIdGetData = {
    body?: never;
    path: {
        /**
         * Edit Id
         */
        edit_id: number;
    };
    query?: never;
    url: '/edits/{edit_id}';
};

export type GetEditEditsEditIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetEditEditsEditIdGetError = GetEditEditsEditIdGetErrors[keyof GetEditEditsEditIdGetErrors];

export type GetEditEditsEditIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateEditEditsEditIdPatchData = {
    body: EditUpdateRequest;
    path: {
        /**
         * Edit Id
         */
        edit_id: number;
    };
    query?: never;
    url: '/edits/{edit_id}';
};

export type UpdateEditEditsEditIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateEditEditsEditIdPatchError = UpdateEditEditsEditIdPatchErrors[keyof UpdateEditEditsEditIdPatchErrors];

export type UpdateEditEditsEditIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RetryEditEditsEditIdRetryPostData = {
    body?: never;
    path: {
        /**
         * Edit Id
         */
        edit_id: number;
    };
    query?: never;
    url: '/edits/{edit_id}/retry';
};

export type RetryEditEditsEditIdRetryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryEditEditsEditIdRetryPostError = RetryEditEditsEditIdRetryPostErrors[keyof RetryEditEditsEditIdRetryPostErrors];

export type RetryEditEditsEditIdRetryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CancelEditEditsEditIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Edit Id
         */
        edit_id: number;
    };
    query?: never;
    url: '/edits/{edit_id}/cancel';
};

export type CancelEditEditsEditIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelEditEditsEditIdCancelPostError = CancelEditEditsEditIdCancelPostErrors[keyof CancelEditEditsEditIdCancelPostErrors];

export type CancelEditEditsEditIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListWorkflowsWorkflowsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Last Id
         */
        last_id?: number;
    };
    url: '/workflows';
};

export type ListWorkflowsWorkflowsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWorkflowsWorkflowsGetError = ListWorkflowsWorkflowsGetErrors[keyof ListWorkflowsWorkflowsGetErrors];

export type ListWorkflowsWorkflowsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type CreateWorkflowWorkflowsPostData = {
    body: VideoWorkflowCreateRequestInput;
    path?: never;
    query?: never;
    url: '/workflows';
};

export type CreateWorkflowWorkflowsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateWorkflowWorkflowsPostError = CreateWorkflowWorkflowsPostErrors[keyof CreateWorkflowWorkflowsPostErrors];

export type CreateWorkflowWorkflowsPostResponses = {
    /**
     * Successful Response
     */
    200: VideoWorkflowCreateRequestOutput;
};

export type CreateWorkflowWorkflowsPostResponse = CreateWorkflowWorkflowsPostResponses[keyof CreateWorkflowWorkflowsPostResponses];

export type DeleteWorkflowWorkflowsWorkflowIdDeleteData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}';
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteWorkflowWorkflowsWorkflowIdDeleteError = DeleteWorkflowWorkflowsWorkflowIdDeleteErrors[keyof DeleteWorkflowWorkflowsWorkflowIdDeleteErrors];

export type DeleteWorkflowWorkflowsWorkflowIdDeleteResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetWorkflowWorkflowsWorkflowIdGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}';
};

export type GetWorkflowWorkflowsWorkflowIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetWorkflowWorkflowsWorkflowIdGetError = GetWorkflowWorkflowsWorkflowIdGetErrors[keyof GetWorkflowWorkflowsWorkflowIdGetErrors];

export type GetWorkflowWorkflowsWorkflowIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type UpdateWorkflowWorkflowsWorkflowIdPatchData = {
    body: WorkflowUpdateRequest;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}';
};

export type UpdateWorkflowWorkflowsWorkflowIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateWorkflowWorkflowsWorkflowIdPatchError = UpdateWorkflowWorkflowsWorkflowIdPatchErrors[keyof UpdateWorkflowWorkflowsWorkflowIdPatchErrors];

export type UpdateWorkflowWorkflowsWorkflowIdPatchResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListWorkflowExecutionsWorkflowsWorkflowIdExecutionsGetData = {
    body?: never;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: {
        /**
         * Limit
         */
        limit?: number;
        /**
         * Last Id
         */
        last_id?: number;
    };
    url: '/workflows/{workflow_id}/executions';
};

export type ListWorkflowExecutionsWorkflowsWorkflowIdExecutionsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListWorkflowExecutionsWorkflowsWorkflowIdExecutionsGetError = ListWorkflowExecutionsWorkflowsWorkflowIdExecutionsGetErrors[keyof ListWorkflowExecutionsWorkflowsWorkflowIdExecutionsGetErrors];

export type ListWorkflowExecutionsWorkflowsWorkflowIdExecutionsGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RetryWorkflowWorkflowsWorkflowIdRetryPostData = {
    body: WorkflowRetryRequest;
    path: {
        /**
         * Workflow Id
         */
        workflow_id: number;
    };
    query?: never;
    url: '/workflows/{workflow_id}/retry';
};

export type RetryWorkflowWorkflowsWorkflowIdRetryPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RetryWorkflowWorkflowsWorkflowIdRetryPostError = RetryWorkflowWorkflowsWorkflowIdRetryPostErrors[keyof RetryWorkflowWorkflowsWorkflowIdRetryPostErrors];

export type RetryWorkflowWorkflowsWorkflowIdRetryPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ExecuteWorkflowWorkflowsExecutePostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Media
         */
        media: string;
        /**
         * Id
         */
        id?: string | null;
        /**
         * Name
         */
        name?: string | null;
        /**
         * Search
         */
        search?: string | null;
    };
    url: '/workflows/execute';
};

export type ExecuteWorkflowWorkflowsExecutePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ExecuteWorkflowWorkflowsExecutePostError = ExecuteWorkflowWorkflowsExecutePostErrors[keyof ExecuteWorkflowWorkflowsExecutePostErrors];

export type ExecuteWorkflowWorkflowsExecutePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};
